pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deploy') {
            steps {
                sh '''
                NAME="demo"
                VERSION="0.0.1-SNAPSHOT"
                echo "${NAME}-${VERSION}"
                java -version
                java -jar target/${NAME}-${VERSION}.jar
                '''
            }
        }
    }
}
